### ISSUE TITLE
Report of all locations

### ISSUE THREAD

**Issue by DavidRoy** [NERC-CEH/dunes-app#10]
To provide an overview across all sites, a report pages is required that gives an overview of all locations.  Available to users with permission = Site manager

**Comment by johnvanbreda** [comment]
@DavidRoy here's a first draft: https://dunescapes.brc.ac.uk/sites/overview-list. Any thoughts on additional columns you need?

**Comment by DavidRoy** [comment]
@johnvanbreda Looks good. Can you add more meaningful label for the two columns labelled 'Quadrats'

**Comment by johnvanbreda** [comment]
Fixed - that was intended to be a count of samples.

**Comment by DavidRoy** [comment]
Thanks.  that's good to have and makes sense to be zero at this point
