### ISSUE TITLE
More helpful approach when users not logged in?

### ISSUE THREAD

**Issue by DavidRoy** [NERC-CEH/dunes-app#13]
Currently, if you are not logged in you can start a survey but when trying to add a site the message is
'You don't have any sites. Please try to refresh the list'.

This is not helpful as the real issue is that the user is not logged in?

Solutions:
1. Make it clear to users that they'll need an account/be logged in to submit surveys
2. Show the list of locations even when users are not logged in?

**Comment by kazlauskis** [comment]
Thanks, we'll improve this.
