### ISSUE TITLE
T&Cs

### ISSUE THREAD

**Issue by DavidRoy** [NERC-CEH/dunes-app#3]
Align with T&Cs being updated for iRecord
https://github.com/BiologicalRecordsCentre/iRecord/issues/638

**Comment by kazlauskis** [comment]
Could this be hosted on the website and the app would just link to? Same with #2.

**Comment by DavidRoy** [comment]
yes, 
.../terms-of-use

**Comment by kazlauskis** [comment]
Excellent, thanks.
