### ISSUE TITLE
Enable OPTIONS request for the Dev and Live warehouses

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/dunes-app#34]
This is probably some IIS config. At the moment, the indicia warehouse code doesn't receive OPTIONS requests and IIS is responding automatically.

**Comment by kazlauskis** [comment]
@BirenRathod is this is something you could have a look? This is quite urgent as it blocks our Dunes App release.

**Comment by BirenRathod** [comment]
@kazlauskis If this has been pass through dunscapes website then it has already got enabled. Do you need on the warehouse?

**Comment by kazlauskis** [comment]
Yes, that's the dev and live warehouses.

**Comment by BirenRathod** [comment]
@kazlauskis Why this app is different than others? Sorry to ask you but no other app has got that requirement.

**Comment by kazlauskis** [comment]
Yes, it is different - it will communicate directly with the warehouse.

**Comment by kazlauskis** [comment]
I am also getting 405 when doing PUT or DELETE: "405 - HTTP verb used to access this page is not allowed." Do you know if this is the IIS and could also be enabled?

**Comment by BirenRathod** [comment]
@kazlauskis 
I have implemented the settings of verb in IIS.

**Comment by kazlauskis** [comment]
Thanks, the OPTIONS now work. The PUT and DELETE though gives`401 - Unauthorized: Access is denied due to invalid credentials.` instead of 405 now. Looks like these two types don't accept Authorization header with my token. GET/POST with the same header works fine though.

**Comment by johnvanbreda** [comment]
@kazlauskis I've just pulled the latest code. I don't think it will change anything but I thought I should mention it as I refactored quite a lot of the code.

**Comment by kazlauskis** [comment]
Thanks, I have tried this and it gives the same 401 when doing PUT and DELETE.

**Comment by johnvanbreda** [comment]
Yes, think that's IIS config again...

**Comment by BirenRathod** [comment]
It has already got both these enabled.

**Comment by kazlauskis** [comment]
Yes, the methods are available, but I get 401 when making the requests. Is there some Authorisation header check that's blocking the requests?

**Comment by BirenRathod** [comment]
Is it on Dev?

**Comment by kazlauskis** [comment]
Yes

**Comment by BirenRathod** [comment]
I haven't made any changes since last verb enabled and it has got all users permission too. Is there anyway, I could test? sorry to ask but I can't see any error in the log files too.

**Comment by kazlauskis** [comment]
Yes, try this with the token I have sent you few days ago:
```
curl --location --request DELETE 'https://devwarehouse.indicia.org.uk/index.php/services/rest/samples/9302827' \
--header 'Authorization: Bearer TOKEN'
```

Change DELETE -> GET to see that it works for other methods.

**Comment by BirenRathod** [comment]
@kazlauskis I implemented the settings little bit and I got this message "404 - File or directory not found.", so something is missing there.

**Comment by BirenRathod** [comment]
More info of  404 ----
"The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable."

**Comment by kazlauskis** [comment]
Yeah, a successful delete will remove the resource thus the 404. Try the PUT instead, this also gives me the 401:

```
curl --location --request PUT 'https://devwarehouse.indicia.org.uk/index.php/services/rest/samples/9302829' \
--header 'Authorization: Bearer TOKEN' \
--header 'Content-Type: application/json' \
--data-raw '{
    "values": {
		"comment": "A sample comment test"
	}
}'
```

**Comment by BirenRathod** [comment]
Same for me.

**Comment by kazlauskis** [comment]
Great, you can now replicate the issue then. Once you resolve the 401 on the IIS then you should get something like 200.

**Comment by BirenRathod** [comment]
@kazlauskis I need to find out about first what to resolve, because it seems like there is a permission issue on one of the folder but looking at the folder there isn't, so some where problem in the either code or PHP settings.

**Comment by kazlauskis** [comment]
The issue here is that an endpoint is not passing on the request to the PHP code but rejecting it with 401 when the authorisation header is present for DELETE and PUT methods. I don't have any access to the IIS anymore so I can't tell you any more than the `401` code I am getting.

<img width="759" alt="Screenshot 2020-09-14 at 21 06 13" src="https://user-images.githubusercontent.com/7383162/93132780-21dc4100-f6ce-11ea-829a-a29db45519e3.png">

 @johnvanbreda do you have any other thoughts why some request methods authorise me while others don't with the same token? That error above is it PHP or IIS?

Thanks to both of you.

**Comment by johnvanbreda** [comment]
I think that error is from IIS. @BirenRathod if you Google for "access is denied due to invalid credentials" there are quite a few links to different reasons why this might occur under IIS.

**Comment by BirenRathod** [comment]
@johnvanbreda I have checked most of them and I'm still trying some but what I don't understand is, why does it need a folder permission to delete record?

**Comment by BirenRathod** [comment]
@johnvanbreda by googling your suggestion, I didn't found any help at all. So I have tried my own expertise using past experience and finally I have cracked down this problem. It is basically combination of folder permission and PHP verb settings.

@kazlauskis I have already deleted above IDs, so you can try any other one. obviously you can add new one, like you did before.

**Comment by johnvanbreda** [comment]
@BirenRathod it's an API end-point so this is nothing to do with a folder permission I suspect - the error message is misleading as it says "directory or page" - by "page" it really means "API end-point". What seems to be happening is that IIS ws pre-filtering the requests and making it's own decision on whether they are permitted or not, even though my code handles that by checking the bearer token. PUT and DELETE are being handled differently by IIS and the request is not even reaching the PHP code. 

Anyway, the good news is I started writing this post about an hour ago and when I came back to finish it, the PUT request started behaving as I expected, so you must have fixed it! Well done!

**Comment by BirenRathod** [comment]
@johnvanbreda About folder permission, that was my question above I asked but it turned out that it does require write permission of files and folder even though it is not doing anything actually on files or folder but IIS making sure that the user of website created on IIS has got all required permissions.

**Comment by kazlauskis** [comment]
Thanks, I can confirm the methods work now. Has this also been fixed in live warehouse?

**Comment by BirenRathod** [comment]
@kazlauskis Not yet, I can do after once I get a confirmation.

**Comment by kazlauskis** [comment]
@johnvanbreda @BirenRathod, In live warehouse I am getting a double `Access-Control-Allow-Origin` header when doing OPTIONS. Any thoughts why this could be?

<img width="437" alt="Screenshot 2020-09-17 at 10 27 48" src="https://user-images.githubusercontent.com/7383162/93452891-de9df000-f8d0-11ea-8022-e0feb0f9786b.png">

**Comment by BirenRathod** [comment]
@kazlauskis Yes, because there is a config added in web.config file to allow request from Geoserver.

Also, just to let you know, I still haven't enabled those setting as I did on dev warehouse to comply with REST API requests.

**Comment by kazlauskis** [comment]
When would you be able to fix this and enable the methods?

**Comment by BirenRathod** [comment]
@kazlauskis 
I'm doing right now.

**Comment by BirenRathod** [comment]
@kazlauskis 
Is it possible to email me the JWT token for live please?

**Comment by kazlauskis** [comment]
I've sent it now, but for some reason the live warehouse gives me 401 Unauthorised with any of the tokens now. I don't think this matters as this doesn't affect the headers.

**Comment by BirenRathod** [comment]
@kazlauskis Thanks for that. Yes, I got same, so I'm investing into that.

**Comment by BirenRathod** [comment]
@kazlauskis For some reason the token you sent me is not working or not right. That is why, I got 401: Unauthorized, "Unable to authorise" message.

**Comment by kazlauskis** [comment]
Yes, it is irrelevant to the OPTIONS issue you're solving. You should not get the double header in the response. Please fix that first.

**Comment by BirenRathod** [comment]
@kazlauskis I'm not resolving double header issue at present. I presume, it is ok if it is there.

**Comment by BirenRathod** [comment]
@kazlauskis As I mentioned above, there is already config added to accept request from Geoserver, so it is easy to remove if that is giving a problem.

**Comment by kazlauskis** [comment]
Yes, please fix it. There shouldn’t be a double header as this breaks CORS.

On 17 Sep 2020, at 15:27, Biren <notifications@github.com> wrote:

﻿

@kazlauskis<https://github.com/kazlauskis> As I mentioned above, there is already config added to accept request from Geoserver, so it is easy to remove if that is giving a problem.

**Comment by BirenRathod** [comment]
@kazlauskis It has fixed. Send me the right token please, so I can able to make right config to accept other verb requests.
