### ISSUE TITLE
No species available to record in app under Scrub and woodland habitat

### ISSUE THREAD

**Issue by sacrevert** [NERC-CEH/dunes-app#38]
@LaurenceJonesES Is this intentional? Not clear from manual.

**Comment by LaurenceJonesES** [comment]
There are no indicator species for these habitats, used in the app, only those listed in the Appendix of the manual. Open to suggestions on how to address this. Could just be a message saying 'no indicator species for this habitat'

**Comment by sacrevert** [comment]
Probably not worth spending app resource on this -- just clarify in the manual somewhere obvious? You can close the issue if that is the case.

**Comment by LaurenceJonesES** [comment]
Will add clarification in the manual.
