### ISSUE TITLE
Three species displaying with unaccepted synonyms

### ISSUE THREAD

**Issue by sacrevert** [NERC-CEH/dunes-app#39]
@kazlauskis @LaurenceJonesES 
[Fixed dune, Health]
Scleropodium purum is given incorrectly for Pseudoscleropodium purum (NHMSYS0000310512)
[Strandline, Health]
Matricaria maritima is given incorrectly for Tripleurospermum maritimum (NHMSYS0000464607)
[Fixed dune, Health]
Odontites verna is given incorrectly for Odontites vernus (NBNSYS0000004164)

**Comment by johnvanbreda** [comment]
@sacrevert shall I update the warehouse data for these taxa? If so, shall I just update the existing name entry (replacing the synonym name with the accepted name and therefore updating all existing records), or should I add a new accepted name and point the old name at it?

**Comment by sacrevert** [comment]
@johnvanbreda All of these already exist in the warehouse (they are common taxa), and appear on iRecord correctly, so I'm a bit confused as to what is required here. Presumably if someone did record under these old names the accepted name would be the one exported anyway? It doesn't seem like a UKSI issue to me

**Comment by DavidRoy** [comment]
The plant lists came from @LaurenceJonesES, maybe thinking about the Dunes community who prefer outdated names ;-)

**Comment by sacrevert** [comment]
Matricaria maritima is not so much an old name as a fossilised one -- it hasn't been that since the 1970s 
; )

**Comment by LaurenceJonesES** [comment]
The plant names were inherited from the original draft citizen science manual produced by NE and NRW staff. Very happy for them all to be updated as required.

**Comment by johnvanbreda** [comment]
I've updated the names on the warehouse. @kazlauskis you can update the names in the app but keep the same taxa_taxon_list_ids.

**Comment by kazlauskis** [comment]
Thanks, I have updated the app now and will close the ticket once it reaches the app stores.
