### ISSUE TITLE
Setup list of Dune site

### ISSUE THREAD

**Issue by DavidRoy** [NERC-CEH/dunes-app#4]
The app requires a list of Dune sites for the user to select.
These need to be loaded into the Indicia warehouse

**Comment by DavidRoy** [comment]
List of sites to setup locations.  Information to use:
1. Set of locations defined by grid reference
2. Location name = Site name
3. Add additional location attribute for = Cluster site

[Summary of Dynamic Dunescapes sites.xlsx](https://github.com/NERC-CEH/dunes-app/files/4896426/Summary.of.Dynamic.Dunescapes.sites.xlsx)

@johnvanbreda can you setup these sites

**Comment by kazlauskis** [comment]
If there was a report for me to pull the list then it would be great.

**Comment by johnvanbreda** [comment]
I've uploaded these sites, location_type set to 17804: Dunscapes site. The custom attribute for Cluster site is ID 262.

@kazlauskis  you could just use one of the standard locations reports, e.g. locations/library/locations_list_3.xml setting the location_type_ids parameter to 17804 and locattrs=262?

@DavidRoy I can't close this issue - please close if OK.

**Comment by kazlauskis** [comment]
I have invited you to the repo now so you should be able to manage the tickets.

**Comment by johnvanbreda** [comment]
@kazlauskis thanks.
