### ISSUE TITLE
Plant quadrat data: Website occurrences download is broken

### ISSUE THREAD

**Issue by sacrevert** [NERC-CEH/dunes-app#40]
@johnvanbreda @LaurenceJonesES 
Website occurrences download for plant quadrat data is broken.
I have entered test data through the app, and, whilst the parent and child sample downloads work, the occurrences zipfile is empty.

**Comment by DavidRoy** [comment]
@johnvanbreda can you pick this one up as a reasonably high priority

**Comment by sacrevert** [comment]
@johnvanbreda @DavidRoy Now working -- turns out there is just a lag relative to the parent and child sample info which worked instantly.

**Comment by DavidRoy** [comment]
There will be a slight lag in records reaching the ElasticSearch index - which is used for the occurrences report
