### ISSUE TITLE
App creating occurrences for zero abundance records in Quadrat survey

### ISSUE THREAD

**Issue by sacrevert** [NERC-CEH/dunes-app#41]
@DavidRoy @LaurenceJonesES 
- ~~Occurrence cover data information is missing from the download.~~
- Parent sample (i.e. plot) ID information is missing from the download.
- ~~Also, there are what I presume to be indicator columns (Health, Nitrogen), which are currently empty. Should this have a 1/0 to indicate whether a species is listed in that category, or the habitat name for which it is that type of indicator? Ideally it would be the latter, although if the former, then the habitat name is required in another column~~

**Comment by sacrevert** [comment]
@DavidRoy @LaurenceJonesES @johnvanbreda 
OK, so re-downloading today gives the cover values in the Health and Nitrogen columns, so maybe this was just another ElasticSearch index build lag.
I think this leaves the two issues below:
- Parent sample (i.e. plot) ID information is missing from the occurrences download
- Plot/sample habitat information missing from the occurrences download

**Comment by sacrevert** [comment]
@johnvanbreda @DavidRoy 
Thanks John, would it be possible to complete these this week? I think these occurrence sample issues were not dealt with under #44

**Comment by johnvanbreda** [comment]
@sacrevert is that OK now?

**Comment by sacrevert** [comment]
Almost there, but I don't really need the following sample level columns in the occurrence download (these are in the child download which is fine since you updated it with the parent ID values):

Grasses | Herbs | Moss & Lichen | Sand | Scrub | Shrubs | Vegetation
-- | -- | -- | -- | -- | -- | --

Also, at the moment the occurrence download includes all the species that are listed in a list for a habitat even if they had a zero cover value. So, e.g., I recorded Hypnum cupressiforme for sample 12015770 (parent = 12015769), but all of the listed Fixed Dune / Health indicators are also included with zero occurrences in the download. I'm surprised to see that these all have occurrence IDs -- is it intentional to create occurrence records for all non-recorded indicator species? (These can be derived from comparing what was recorded with the habitat/indicator lists anyway of course). @kazlauskis @DavidRoy @johnvanbreda @LaurenceJonesES

**Comment by LaurenceJonesES** [comment]
We shouldn't need to download non-recorded, but where someone enters '0' abundance, that's useful to show it has been noted, rather than forgotten. I'm thinking more specifically about bare sand in this instance, and the recording of categories like shrubs which also require aggregate cover to be recorded.

**Comment by sacrevert** [comment]
@LaurenceJonesES Those elements of bulk cover are at the child sample level, this issue is restricted to the species occurrences download only. If you want people to explicitly enter zero to indicate that they have not forgotten the question, then those sliders should be made mandatory in the app - at the moment they can either be left blank and zero will be inferred, or a zero will be explicitly provided. If you want to make them mandatory (i.e. zero is required as an entry), whereby you should also probably change the header information on the slider pages, then can you open a new issue for @kazlauskis

**Comment by johnvanbreda** [comment]
I've removed the columns. I think the question about zero occurrences is a separate issue to the downloads.

**Comment by kazlauskis** [comment]
@sacrevert yes, at the moment, the app sends a full list of occurrences for the habitat. But this wasn't done intentionally, rather a simpler approach to building a list for the habitat.

**Comment by sacrevert** [comment]
@kazlauskis Shall i open a new issue for this? Is it something that can be easily changed?

**Comment by LaurenceJonesES** [comment]
Leaving out zero records can be automated if that's an issue currently; probably need a wider discussion on what to make compulsory or not, so let's park that issue for a few months until more feedback received.

**Comment by sacrevert** [comment]
@LaurenceJonesES We need to clearly separate issues on here so that they are manageable. I will create a new issue for the sample cover properties in relation to mandatory zeros, noting that a decision is pending. The occurrences issue should be solved, because having occurrence records that are zero abundance is not ideal for the wider indicia warehouse in my opinion, and is the kind of thing that leads to a lot of confusion downstream.

**Comment by sacrevert** [comment]
@kazlauskis just to note that I have renamed this to solely address this issue. Not sure whether it is resolvable easily or not?

**Comment by kazlauskis** [comment]
Great, thanks, this shouldn't be too hard to change. I will leave it to others to prioritise.

**Comment by sacrevert** [comment]
@kazlauskis I think it is desirable in that we don't want to be filling the database with absence records, and required for downstream processing of occurrence downloads, so, assuming that we have budget, it would be good to implement as soon as possible. 
@DavidRoy

**Comment by DavidRoy** [comment]
@kazlauskis I agree with Oli.  Even though the data volumes for this app are likely to be low, it's cleaner to implement as @sacrevert suggest.  We can cover from other budgets if it's an issue for DD

**Comment by kazlauskis** [comment]
Thanks, I will change the app to skip creating empty occurrences.
