### ISSUE TITLE
Disturbance surveys not uploading - Android 8.1.0

### ISSUE THREAD

**Issue by sacrevert** [NERC-CEH/dunes-app#42]
@DavidRoy @kazlauskis @johnvanbreda @LaurenceJonesES 
Not sure whether these are related but:
- ~~None of the data in the website disturbance download dataset have any grid refs (I presume that it is a required field of the survey?)~~ - solved under NERC-CEH/dunes-app#44 
- Trying to test this on my phone by adding a new record with a grid ref, I've found that submission fails (survey stays on Pending page, despite the loading/syncing graphic appearing briefly). Also, the record fails (so far) to appear in the database download.

Not having the grid refs might not be a major issue if the download included the site name and all one wanted was a barchart of disturbance records over time, or a piechart/whatever of type proportions, at a site;,but presumably managers would want the grid refs for their own management purposes, even if they are not used in visual feedback of data.

**Comment by sacrevert** [comment]
From @LaurenceJonesES (#44 )
>Disturbance: Site managers will want grid refs for Disturbance records

**Comment by sacrevert** [comment]
Possibly now this issue only relates to the app @kazlauskis but I will retest.

Update: new disturbance item still not uploading through app (remains as pending).
Phone spec: Android 8.1.0 (security patch to 1/Feb/2019), Moto G5

**Comment by kazlauskis** [comment]
@sacrevert try updating the app to the latest - v1.0.0-6. It should have the disturbance fixed now.
