### ISSUE TITLE
Distubance survey map backdrop missing

### ISSUE THREAD

**Issue by sacrevert** [NERC-CEH/dunes-app#43]
@kazlauskis @LaurenceJonesES @DavidRoy 
When conducting a Disturbance survey, the Location option map doesn't show any backdrop (unlike e.g. the Plant quadrat survey, which does show a satellite backdrop.

I presume this wasn't intentional?

**Comment by kazlauskis** [comment]
Thanks for raising this, I will fix it.

**Comment by sacrevert** [comment]
I think the same issue is happening with the grid ref field under the point addition functionality in the Dune zonation and Dune profile surveys
