### ISSUE TITLE
General issues with downloads

### ISSUE THREAD

**Issue by sacrevert** [NERC-CEH/dunes-app#44]
@johnvanbreda @DavidRoy @LaurenceJonesES  Some thoughts on the download page below
- Dipwell samples -- It would be more straightforward for subsequent processing if there was just one file that included the parent sample (location) ID and the Grid_ref_calculated at the occurrence level. At the moment the child file doesn't include the parent sample ID for joining to get the grid ref
- Plant quadrat cover data (occurrences dealt with in #41) -- Again, It would be more straightforward for subsequent processing if there was just one file that included the parent Sample ID and the Grid_ref_calculated at the child sample information level. At the moment the child file doesn't include the parent Sample ID for joining to get the grid ref: would it be possible to have single download with the parent sample ID and grid ref duplicated for each row? (Note that currently the ‘child’ quadrat cover information for the different vegetation types is duplicated because of the 5 different vegetation height estimates, but I don’t think this is worth splitting out, downstream processing can deal with that).
- Dune zonation survey – again, one download including both parent sample (plot) ID and sample ID would be far more convenient. (Also, transition grid refs are not included, although I doubt these will be that useful anyway given that often phone GPSs are not returning good fixes (my test recorded two at 100 m resolution)).
- Dune profile survey – again, one download including both parent sample (plot) ID and sample ID needed. (Again, change point grid refs not in download).
- Also, none of the downloads have site (or transect) name information in them.

**Comment by LaurenceJonesES** [comment]
Zonation & Profile surveys: Would be useful to include change point grid refs in the download, mainly to give the option of checking rough locations later

Disturbance: Site managers will want grid refs for Disturbance records

**Comment by johnvanbreda** [comment]
For all the child sample reports, I've added the grid_ref_calculated column but note that this is for the child sample as stored by the app, not the parent sample. So there might be discrepancies. I also added the parent_sample_id into the child sample reports so they can be linked.

I've added Site info to the sample downloads where it is available.

I've added a grid_ref_stored column to the sample reports, resolving the issue where the calculated grid ref has not been stored in the disturbance data.

Still to do - Zonation & Profile surveys: Would be useful to include change point grid refs in the download, mainly to give the option of checking rough locations later

**Comment by sacrevert** [comment]
@johnvanbreda @DavidRoy 
Thanks John, would it be possible to complete these this week?

**Comment by johnvanbreda** [comment]
@sacrevert I'm not sure what change point grid refs are - are they what the app stores in "Grid ref. calculated"? If so then these are included in the child sample downloads.

**Comment by sacrevert** [comment]
@johnvanbreda Yes, you are right, the addition of Gridref_calculated solved that one too
