### ISSUE TITLE
Uploading media returns error screen

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/dunes-app#52]
POST to `media-queue` gets this screen:

<img width="513" alt="Screenshot 2020-11-03 at 17 08 58" src="https://user-images.githubusercontent.com/7383162/98017513-45cb2180-1df7-11eb-9d62-d0b3dcfa7bd0.png">

**Comment by kazlauskis** [comment]
@johnvanbreda do you know if this is the IIS or the warehouse?

**Comment by johnvanbreda** [comment]
I think a folder permissions issue - can you try now please?

**Comment by kazlauskis** [comment]
Thanks, works well now.
