### ISSUE TITLE
Water table depths -- website downloads

### ISSUE THREAD

**Issue by sacrevert** [NERC-CEH/dunes-app#58]
Request for additional information in child sample download.

When locations are set up on the website e.g. [see](https://dunescapes.brc.ac.uk/sites/setup/fixed-point-edit?location_id=248047&dynamic-parent_id=247268)
Fixed point labels and group names are also set. Can these be included in the download please.
At the moment the fixed point label is appended to the site name, but it would be useful to have these separated out e.g. for the above example
Site | Fixed point label | Group name
Baglan Burrows | Dipwell 1 | Coast dipwells
@johnvanbreda @LaurenceJonesES

**Comment by johnvanbreda** [comment]
Done
