### ISSUE TITLE
Dune zonation mapping -- website downloads

### ISSUE THREAD

**Issue by sacrevert** [NERC-CEH/dunes-app#59]
I'm a little confused by this one, as I have uploaded test data under this survey for Baglan Burrows, Transect name "Southern", but the download is not populating the site name at the moment. I presume this just needs an SQL fix somewhere?

Also, can we add the Transect name to the download, e.g. the field that has "Southern" [here](https://dunescapes.brc.ac.uk/sites/setup/transect-edit?location_id=248041&dynamic-parent_id=247268)

Thanks @johnvanbreda 
cc @LaurenceJonesES

**Comment by johnvanbreda** [comment]
Done
