### ISSUE TITLE
Website - map selection

### ISSUE THREAD

**Issue by DavidRoy** [NERC-CEH/dunes-app#66]
From Andy Nelson:
when using the “?” tool on the map, I can select datapoints on the map (shown red in the image below) but I’m not sure how to access this selection of locations? The accompanying table doesn’t seem to change in any way? Am I missing something (quite possible) or is there an issue with this?

![an](https://user-images.githubusercontent.com/2699478/98918879-12a72300-24c6-11eb-82af-de6c2e0b72b8.png)

**Comment by johnvanbreda** [comment]
Fixed.
