### ISSUE TITLE
Additional site manager download - data from iRecord

### ISSUE THREAD

**Issue by DavidRoy** [NERC-CEH/dunes-app#70]
Where dunesite boundaries are available.
An occurrence download for any iRecord records that intersect with site boundary.
Available as additional download - https://dunescapes.brc.ac.uk/downloads

**Comment by johnvanbreda** [comment]
Will this be a single download for all dune sites, or can we have a drop-down to choose the site? The latter might be easier so we don't run an over-complex spatial query (since dune site boundaries are not indexed).

**Comment by DavidRoy** [comment]
Latter is fine, where users choose the site first. Only available for sites where we have a boundary

**Comment by johnvanbreda** [comment]
Now done. I've also moved the old Elasticsearch quadrat occurrences download to the bottom of the form as they will both be affected by the site selector.
