### ISSUE TITLE
Dunesite overview report - values too high

### ISSUE THREAD

**Issue by DavidRoy** [NERC-CEH/dunes-app#71]
https://dunescapes.brc.ac.uk/sites/overview-list

Shows samples for South Watney to be >1000 quadrats.  However, there are only a handful of records in the quadrat download file.

@johnvanbreda can you confirm what is in the summary report?  Does it include training data for example?

**Comment by johnvanbreda** [comment]
Fixed. Joins in the SQL were causing the aggregate functions to multiply up.
