### ISSUE TITLE
Downloads page

### ISSUE THREAD

**Issue by DavidRoy** [NERC-CEH/dunes-app#8]
Initial requirement is downloads for:
1. Transect routes (.shp)
2. Samples (.csv)
3. Occurrences (.csv)
4. Photos (.csv) - occurrence/sample IDs plus image url

**Comment by DavidRoy** [comment]
@johnvanbreda can you advise on when you can produce these downloads

**Comment by johnvanbreda** [comment]
I'll work on them now.

**Comment by johnvanbreda** [comment]
@DavidRoy - 
1. Please let me know what columns to include in the occurrences download.
2. For the samples download, again, what columns? Also is this a download of the individual point samples, or the parent transect samples?

**Comment by kazlauskis** [comment]
1. The only occurrences we send is for Plant Quadrat survey where an occurrence has a taxon, plus health (`occAttr:841`) and nitrogen (`occAttr:840`) values.

**Comment by DavidRoy** [comment]
@johnvanbreda 
1. The main principle is that everything collected through the surveys needs to be included in the download files - split by samples and occurrences.  Most information is at the sample level
2. Both.  If it is easier to split the downloads by survey type that is fine

**Comment by johnvanbreda** [comment]
Thanks both. @kazlauskis - are all the surveys going to submit a parent/child sample, or are some of them just single level?

**Comment by kazlauskis** [comment]
Disturbance is flat - just a sample. Otherwise, all sample->subsample->occurrence.

**Comment by johnvanbreda** [comment]
@DavidRoy there is a Downloads page on the menu now. It will need testing and tweaking though once there are some data to download.
