### ISSUE TITLE
Add new dune site: Pembrey burrows

### ISSUE THREAD

**Issue by DavidRoy** [NERC-CEH/dunes-app#80]
Add new site to the list of type - Dunescapes site

Name = Pembrey burrows
Site boundary file = 
[PembreyBurrows_SoLIFE_Boundary (1).zip](https://github.com/NERC-CEH/dunes-app/files/8570586/PembreyBurrows_SoLIFE_Boundary.1.zip)
Central gridref = SS 41295 99304

**Comment by DavidRoy** [comment]
Second site to add
Name = Newborough Warren
Site boundary file = 
[Warren Shapefile.zip](https://github.com/NERC-CEH/dunes-app/files/8730452/Warren.Shapefile.zip)
Central gridref = SH 42282 63502

**Comment by johnvanbreda** [comment]
@DavidRoy I've done Pembury Burrows. The Newbourough Warren SHP files has a DBF with no name for the location in it - can you re-export this please with at least 1 attribute value I can use as the name.

**Comment by DavidRoy** [comment]
@johnvanbreda can you setup newborough without the spatial boundary, I.e. just centroid

**Comment by johnvanbreda** [comment]
Done. I managed to hack the boundary out of the file and apply it to the location using PostGIS and QGIS.
