### ISSUE TITLE
Site setup form - map to zoomed out further on load

### ISSUE THREAD

**Issue by DavidRoy** [NERC-CEH/dunes-app#9]
Can the default zoom for the individual site map, be set higher, e.g. 5/6 level of zoom so the whole site is visible when the page is first loaded
https://dunescapes.brc.ac.uk/sites/setup?dynamic-parent_id=247287

**Comment by johnvanbreda** [comment]
@DavidRoy we don't have the site boundaries loaded, only the centroid. The system currently zooms to fit around the available data for the site, i.e. all the transects, fixed points and the centroid itself, so will become more accurate as the subsites are populated. Is that OK?

**Comment by DavidRoy** [comment]
@johnvanbreda.  Thanks, that will work so no action needed
